### ISSUE TITLE
Change request for Security hardening guide for NetApp ONTAP 9 | TR-4569

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap-whatsnew#20]
Page: [Technical Resources](https://docs.netapp.com/us-en/ontap-whatsnew/ontap98fo_technical_resources.html)
Hi Docs Team,

I would like to report a change request for the document Security hardening guide for NetApp ONTAP 9 | TR-4569. There is conflicting information on pages 7 & 8 regarding the admin account. The document says you can't remove built-in accounts like the admin account, which is correct and advises to lock it instead.

Later on, the document says to create a NewAdmin user and delete the existing admin user. You can perform this, but the admin account returns after a reboot/update. Here is my testing on this:
https://netapp-my.sharepoint.com/:t:/p/sdowling/EZI__uVfTelEuf8Jd7GQCvUB3eBN33UHA4b__WoyeqiDGw?e=WovNk5

The following bug also confirms that it's expected that the admin users for HTTP and ontapi are supposed to return on a reboot:
https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1332310

It might be best to recommend locking the admin account and leaving it on the system instead of deleting it.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Sean -- we're looking into it.

**Comment by netapp-ehoffman** [comment]
Thanks Mark. Hi @sdowling03: I'm connecting you via NetApp email to the appropriate content owner for this request. Thank you for reaching with this feedback!
Ed
