### ISSUE TITLE
generate fr and de - 603

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/ontap-whatsnew#21]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - I kicked this one off manually as the smallest in the list for today, after the other failure.

**Comment by netapp-gudugunti** [comment]
Site is up and running.
Total TOT: 6 minutes.
