### ISSUE TITLE
Broken link to TR-4597 at bottom of page

### ISSUE THREAD

**Issue by kevin-hoke** [NetAppDocs/ontap-whatsnew#22]
Page: [VMware Virtualization](https://docs.netapp.com/us-en/ontap-whatsnew/ontap98fo_vmware_virtualization.html)

At the bottom of this page, there is a link for TR-4597 that points to: 
https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html

The correct link is:
https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html

**Comment by netapp-ahibbard** [comment]
Thanks for reporting this @kevin-hoke . The link has been updated
